"""add codex id verification system

Revision ID: 283392952bc9
Revises: 202608150005
Create Date: 2026-09-19 16:37:30.910012
"""
from alembic import op
import sqlalchemy as sa


revision = '283392952bc9'
down_revision = '202608150005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('session_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'closed')", name='ck_attendance_sessions_status_valid'),
    sa.CheckConstraint('ends_at IS NULL OR ends_at > starts_at', name='ck_attendance_sessions_time_valid'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_sessions_created_by'), 'attendance_sessions', ['created_by'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_session_type'), 'attendance_sessions', ['session_type'], unique=False)
    op.create_index(op.f('ix_attendance_sessions_status'), 'attendance_sessions', ['status'], unique=False)
    op.create_table('codex_student_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('codex_id', sa.String(length=20), nullable=False),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'suspended', 'revoked')", name='ck_codex_student_ids_status_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codex_student_ids_codex_id'), 'codex_student_ids', ['codex_id'], unique=True)
    op.create_index(op.f('ix_codex_student_ids_qr_token'), 'codex_student_ids', ['qr_token'], unique=True)
    op.create_index(op.f('ix_codex_student_ids_status'), 'codex_student_ids', ['status'], unique=False)
    op.create_index(op.f('ix_codex_student_ids_user_id'), 'codex_student_ids', ['user_id'], unique=True)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_identity_id', sa.Integer(), nullable=False),
    sa.Column('scanned_by', sa.Integer(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verification_method', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.CheckConstraint("status IN ('present', 'absent', 'excused')", name='ck_attendance_records_status_valid'),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_identity_id'], ['codex_student_ids.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_identity_id', name='uq_attendance_records_session_student')
    )
    op.create_index(op.f('ix_attendance_records_session_id'), 'attendance_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_status'), 'attendance_records', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_identity_id'), 'attendance_records', ['student_identity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_student_identity_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_status'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_session_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_codex_student_ids_user_id'), table_name='codex_student_ids')
    op.drop_index(op.f('ix_codex_student_ids_status'), table_name='codex_student_ids')
    op.drop_index(op.f('ix_codex_student_ids_qr_token'), table_name='codex_student_ids')
    op.drop_index(op.f('ix_codex_student_ids_codex_id'), table_name='codex_student_ids')
    op.drop_table('codex_student_ids')
    op.drop_index(op.f('ix_attendance_sessions_status'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_session_type'), table_name='attendance_sessions')
    op.drop_index(op.f('ix_attendance_sessions_created_by'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    # ### end Alembic commands ###
